// One-time compatibility shim for diagrams saved before network artwork moved
// to LibraryAsset/S3. New catalog entries never need to be added here.
export const LEGACY_NETWORK_DEVICE_NODE_TYPES = [
  'NetworkRouterNode',
  'NetworkWirelessRouterNode',
  'NetworkLayer2SwitchNode',
  'NetworkLayer3SwitchNode',
  'NetworkHubNode',
  'NetworkBridgeNode',
  'NetworkGatewayNode',
  'NetworkModemNode',
  'NetworkAccessPointNode',
  'NetworkWirelessLanControllerNode',
  'NetworkFirewallNode',
  'NetworkIdsIpsNode',
  'NetworkVpnGatewayNode',
  'NetworkLoadBalancerNode',
  'NetworkProxyNode',
  'NetworkNatGatewayNode',
  'NetworkDesktopPcNode',
  'NetworkLaptopNode',
  'NetworkPrinterNode',
  'NetworkIpPhoneNode',
  'NetworkSmartphoneNode',
  'NetworkTabletNode',
  'NetworkIotDeviceNode',
  'NetworkIpCameraNode',
  'NetworkServerNode',
  'NetworkDatabaseServerNode',
  'NetworkNasStorageNode',
  'NetworkInternetNode',
  'NetworkCloudNode',
  'NetworkIspNode',
  'NetworkDataCenterNode',
  'NetworkBranchOfficeNode',
  'NetworkCellularTowerNode',
  'NetworkSatelliteNode',
] as const;
